version: '2'

services:
  master:
    image: crossz/redis-sentinel-distributed
    environment:
      - APPENDFSYNC=everysec
      - REQUIREPASS=12345678
      - CLIENTPORT=6379
      - CLIENTHOST=master
      - MASTERHOST=
      - MASTERPORT=
    ports:
      - '6379:6379'
    volumes:
      - "/tmp/6379:/data"
      
  slave:
    image: crossz/redis-sentinel-distributed
    environment:
      - APPENDFSYNC=everysec
      - REQUIREPASS=12345678
      - CLIENTHOST=slave
      - CLIENTPORT=6479
      - MASTERHOST=master
      - MASTERPORT=6379
    ports:
      - '6479:6479'
    volumes:
      - "/tmp/6479:/data"