version: '2'

services:
  master:
    build: 
      context: .
      args: 
        - REQUIREPASS=12345678
        - CLIENTPORT=6479
        - MASTERPORT=
        - MASTERHOST=localhost
    environment:
      - REQUIREPASS=12345678
      - CLIENTPORT=6479
      - MASTERPORT=
      - MASTERHOST=localhost
    volumes:
      - "/tmp/6479:/data"
    network_mode: "host"
    image: crossz/redis-sentinel-distributed

  slave:
    build: 
      context: .
      args: 
        - REQUIREPASS=12345678
        - CLIENTPORT=6579
        - MASTERPORT=6479
        - MASTERHOST=localhost
    environment:
      - REQUIREPASS=12345678
      - CLIENTPORT=6579
      - MASTERPORT=6479
      - MASTERHOST=localhost
    volumes:
      - "/tmp/6579:/data"
    network_mode: "host"
    image: crossz/redis-sentinel-distributed




